2020-05-01 22:45:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-01 22:45:17 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds.
2020-05-01 22:45:17 INFO (MainThread) [homeassistant.setup] Setting up http
2020-05-01 22:45:17 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2020-05-01 22:45:17 INFO (MainThread) [homeassistant.setup] Setting up system_log
2020-05-01 22:45:17 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2020-05-01 22:45:18 INFO (MainThread) [homeassistant.setup] Setting up recorder
2020-05-01 22:45:18 INFO (MainThread) [homeassistant.setup] Setting up webhook
2020-05-01 22:45:18 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2020-05-01 22:45:19 INFO (MainThread) [homeassistant.setup] Setting up alexa
2020-05-01 22:45:19 INFO (MainThread) [homeassistant.setup] Setup of domain alexa took 0.0 seconds.
2020-05-01 22:45:19 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 1.5 seconds.
2020-05-01 22:45:19 INFO (SyncWorker_16) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2020-05-01 22:45:19 INFO (SyncWorker_18) [homeassistant.loader] Loaded homekit from homeassistant.components.homekit
2020-05-01 22:45:19 INFO (SyncWorker_18) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2020-05-01 22:45:20 INFO (SyncWorker_3) [homeassistant.loader] Loaded device_tracker from homeassistant.components.device_tracker
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up cloud
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.2 seconds.
2020-05-01 22:45:28 INFO (SyncWorker_17) [homeassistant.loader] Loaded template from homeassistant.components.template
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.0 seconds.
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up zone
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up input_number
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up updater
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up input_text
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up met
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.0 seconds.
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up sun
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up modbus
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up group
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up script
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2020-05-01 22:45:28 INFO (MainThread) [homeassistant.setup] Setting up input_select
2020-05-01 22:45:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for melcloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up climate
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up scene
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up tuya
2020-05-01 22:45:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up switch
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.components.climate] Setting up climate.melcloud
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.components.switch] Setting up switch.localtuya
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.components.switch] Setting up switch.localtuya
2020-05-01 22:45:29 INFO (SyncWorker_5) [pytuya] pytuya version 7.0.5
2020-05-01 22:45:29 INFO (SyncWorker_5) [pytuya] Python 3.7.7 (default, Apr 30 2020, 09:20:07) 
[GCC 6.3.0 20170516] on linux
2020-05-01 22:45:29 INFO (SyncWorker_5) [pytuya] Using pyaes version [1, 3, 0]
2020-05-01 22:45:29 INFO (SyncWorker_5) [pytuya] Using pyaes from '/home/pi/homeassistant/lib/python3.7/site-packages/pyaes/__init__.py'
2020-05-01 22:45:29 DEBUG (SyncWorker_5) [custom_components.localtuya.switch] LocalTUYA: device_id host local_key
2020-05-01 22:45:29 DEBUG (SyncWorker_7) [custom_components.localtuya.switch] LocalTUYA: device_id host local_key
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up person
2020-05-01 22:45:29 INFO (SyncWorker_15) [homeassistant.loader] Loaded rest from homeassistant.components.rest
2020-05-01 22:45:29 INFO (SyncWorker_17) [homeassistant.loader] Loaded weather from homeassistant.components.weather
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up automation
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds.
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.7 seconds.
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up api
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setting up history
2020-05-01 22:45:29 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2020-05-01 22:45:30 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2020-05-01 22:45:30 INFO (MainThread) [homeassistant.setup] Setting up config
2020-05-01 22:45:30 INFO (MainThread) [homeassistant.setup] Setting up system_health
2020-05-01 22:45:30 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2020-05-01 22:45:30 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for mitemp_bt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setting up sensor
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setting up weather
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.0 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 2.8 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 2.7 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 2.5 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 2.5 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 2.5 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.template
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 2.5 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 2.5 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setting up auth
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2020-05-01 22:45:31 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '16', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:45:31 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setting up search
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.0 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.template
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.rest
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.template
2020-05-01 22:45:31 DEBUG (SyncWorker_10) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mitemp_bt
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.components.weather] Setting up weather.met
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain api took 2.1 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain config took 1.6 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setting up mqtt
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain mqtt took 0.0 seconds.
2020-05-01 22:45:31 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 3.3 seconds.
2020-05-01 22:45:32 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 3.1 seconds.
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setup of domain tuya took 3.2 seconds.
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.mqtt
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 3.4 seconds.
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tuya
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setup of domain modbus took 3.5 seconds.
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.modbus
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setup of domain person took 3.5 seconds.
2020-05-01 22:45:32 INFO (SyncWorker_11) [homeassistant.loader] Loaded spotify from homeassistant.components.spotify
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.5 seconds.
2020-05-01 22:45:32 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {}
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 4.4 seconds.
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 2.8 seconds.
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.2 seconds.
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.setup] Setting up cast
2020-05-01 22:45:33 INFO (MainThread) [homeassistant.setup] Setup of domain cast took 0.0 seconds.
2020-05-01 22:45:34 DEBUG (SyncWorker_0) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 22:45:34 INFO (MainThread) [homeassistant.setup] Setting up media_player
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain media_player took 0.1 seconds.
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.cast
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up frontend
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds.
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.1 seconds.
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up map
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.0 seconds.
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up panel_custom
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up logbook
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.0 seconds.
2020-05-01 22:45:35 INFO (SyncWorker_5) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain panel_custom took 0.2 seconds.
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up default_config
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.0 seconds.
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setting up notify
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds.
2020-05-01 22:45:35 INFO (SyncWorker_18) [pychromecast] Querying device status
2020-05-01 22:45:35 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2020-05-01 22:45:36 INFO (MainThread) [homeassistant.setup] Setting up hacs
2020-05-01 22:45:36 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 0.0 seconds.
2020-05-01 22:45:36 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.24.3
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-05-01 22:45:37 DEBUG (SyncWorker_0) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 22:45:37 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 6.4 seconds.
2020-05-01 22:45:38 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-05-01 22:45:38 INFO (MainThread) [hacs.data] Restore started
2020-05-01 22:45:41 INFO (MainThread) [hacs.data] Restore done
2020-05-01 22:45:41 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-05-01 22:45:41 INFO (SyncWorker_12) [homeassistant.loader] Loaded onvif from homeassistant.components.onvif
2020-05-01 22:45:41 INFO (SyncWorker_8) [homeassistant.loader] Loaded ffmpeg from homeassistant.components.ffmpeg
2020-05-01 22:45:41 INFO (SyncWorker_15) [homeassistant.loader] Loaded google_translate from homeassistant.components.google_translate
2020-05-01 22:45:41 INFO (MainThread) [homeassistant.setup] Setting up tts
2020-05-01 22:45:41 INFO (MainThread) [homeassistant.setup] Setting up camera
2020-05-01 22:45:41 INFO (MainThread) [homeassistant.setup] Setting up ffmpeg
2020-05-01 22:45:41 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.4 seconds.
2020-05-01 22:45:42 INFO (MainThread) [homeassistant.setup] Setup of domain ffmpeg took 0.6 seconds.
2020-05-01 22:45:55 INFO (MainThread) [homeassistant.setup] Setup of domain camera took 13.4 seconds.
2020-05-01 22:45:55 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 38.38s
2020-05-01 22:45:55 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2020-05-01 22:45:55 WARNING (MainThread) [homeassistant.components.template.binary_sensor] Could not render template BT, the state is unknown
2020-05-01 22:45:55 INFO (SyncWorker_4) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2020-05-01 22:45:55 INFO (MainThread) [homeassistant.core] Timer:starting
2020-05-01 22:45:57 INFO (SyncWorker_17) [homeassistant.loader] Loaded tplink from homeassistant.components.tplink
2020-05-01 22:45:57 INFO (SyncWorker_1) [homeassistant.loader] Loaded transmission from homeassistant.components.transmission
2020-05-01 22:45:58 INFO (SyncWorker_11) [homeassistant.loader] Loaded emulated_roku from homeassistant.components.emulated_roku
2020-05-01 22:45:58 INFO (MainThread) [hacs] Loading known repositories
2020-05-01 22:45:58 INFO (SyncWorker_11) [homeassistant.loader] Loaded geonetnz_volcano from homeassistant.components.geonetnz_volcano
2020-05-01 22:45:58 INFO (SyncWorker_12) [homeassistant.loader] Loaded powerwall from homeassistant.components.powerwall
2020-05-01 22:45:58 INFO (SyncWorker_18) [homeassistant.loader] Loaded ecobee from homeassistant.components.ecobee
2020-05-01 22:45:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded airly from homeassistant.components.airly
2020-05-01 22:45:58 INFO (SyncWorker_16) [homeassistant.loader] Loaded vesync from homeassistant.components.vesync
2020-05-01 22:45:58 INFO (SyncWorker_7) [homeassistant.loader] Loaded cert_expiry from homeassistant.components.cert_expiry
2020-05-01 22:45:58 INFO (SyncWorker_7) [homeassistant.loader] Loaded rainmachine from homeassistant.components.rainmachine
2020-05-01 22:45:58 INFO (SyncWorker_14) [homeassistant.loader] Loaded samsungtv from homeassistant.components.samsungtv
2020-05-01 22:45:58 INFO (SyncWorker_3) [homeassistant.loader] Loaded izone from homeassistant.components.izone
2020-05-01 22:45:58 INFO (SyncWorker_15) [homeassistant.loader] Loaded notion from homeassistant.components.notion
2020-05-01 22:45:58 INFO (SyncWorker_8) [homeassistant.loader] Loaded life360 from homeassistant.components.life360
2020-05-01 22:45:58 INFO (SyncWorker_17) [homeassistant.loader] Loaded plex from homeassistant.components.plex
2020-05-01 22:45:58 INFO (SyncWorker_19) [homeassistant.loader] Loaded ring from homeassistant.components.ring
2020-05-01 22:45:58 INFO (SyncWorker_4) [homeassistant.loader] Loaded openuv from homeassistant.components.openuv
2020-05-01 22:45:58 INFO (SyncWorker_9) [homeassistant.loader] Loaded somfy from homeassistant.components.somfy
2020-05-01 22:45:58 INFO (SyncWorker_16) [homeassistant.loader] Loaded tesla from homeassistant.components.tesla
2020-05-01 22:45:58 INFO (SyncWorker_13) [homeassistant.loader] Loaded harmony from homeassistant.components.harmony
2020-05-01 22:45:58 INFO (SyncWorker_2) [homeassistant.loader] Loaded plaato from homeassistant.components.plaato
2020-05-01 22:45:58 INFO (SyncWorker_3) [homeassistant.loader] Loaded homematicip_cloud from homeassistant.components.homematicip_cloud
2020-05-01 22:45:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded unifi from homeassistant.components.unifi
2020-05-01 22:45:58 INFO (SyncWorker_8) [homeassistant.loader] Loaded opentherm_gw from homeassistant.components.opentherm_gw
2020-05-01 22:45:58 INFO (SyncWorker_12) [homeassistant.loader] Loaded homekit_controller from homeassistant.components.homekit_controller
2020-05-01 22:45:58 INFO (SyncWorker_18) [homeassistant.loader] Loaded griddy from homeassistant.components.griddy
2020-05-01 22:45:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded august from homeassistant.components.august
2020-05-01 22:45:58 INFO (SyncWorker_5) [homeassistant.loader] Loaded toon from homeassistant.components.toon
2020-05-01 22:45:58 INFO (SyncWorker_5) [homeassistant.loader] Loaded axis from homeassistant.components.axis
2020-05-01 22:45:58 INFO (SyncWorker_16) [homeassistant.loader] Loaded dynalite from homeassistant.components.dynalite
2020-05-01 22:45:58 INFO (SyncWorker_13) [homeassistant.loader] Loaded ambient_station from homeassistant.components.ambient_station
2020-05-01 22:45:58 INFO (SyncWorker_2) [homeassistant.loader] Loaded smartthings from homeassistant.components.smartthings
2020-05-01 22:45:58 INFO (SyncWorker_3) [homeassistant.loader] Loaded hue from homeassistant.components.hue
2020-05-01 22:45:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded minecraft_server from homeassistant.components.minecraft_server
2020-05-01 22:45:59 INFO (SyncWorker_8) [homeassistant.loader] Loaded gpslogger from homeassistant.components.gpslogger
2020-05-01 22:45:59 INFO (SyncWorker_12) [homeassistant.loader] Loaded elkm1 from homeassistant.components.elkm1
2020-05-01 22:45:59 INFO (SyncWorker_19) [homeassistant.loader] Loaded konnected from homeassistant.components.konnected
2020-05-01 22:45:59 INFO (SyncWorker_1) [homeassistant.loader] Loaded heos from homeassistant.components.heos
2020-05-01 22:45:59 INFO (SyncWorker_6) [homeassistant.loader] Loaded gdacs from homeassistant.components.gdacs
2020-05-01 22:45:59 INFO (SyncWorker_7) [homeassistant.loader] Loaded starline from homeassistant.components.starline
2020-05-01 22:45:59 INFO (SyncWorker_14) [homeassistant.loader] Loaded luftdaten from homeassistant.components.luftdaten
2020-05-01 22:45:59 INFO (SyncWorker_10) [homeassistant.loader] Loaded meteo_france from homeassistant.components.meteo_france
2020-05-01 22:45:59 INFO (SyncWorker_15) [homeassistant.loader] Loaded myq from homeassistant.components.myq
2020-05-01 22:45:59 INFO (SyncWorker_11) [homeassistant.loader] Loaded glances from homeassistant.components.glances
2020-05-01 22:45:59 INFO (SyncWorker_17) [homeassistant.loader] Loaded icloud from homeassistant.components.icloud
2020-05-01 22:45:59 INFO (SyncWorker_18) [homeassistant.loader] Loaded almond from homeassistant.components.almond
2020-05-01 22:45:59 INFO (SyncWorker_18) [homeassistant.loader] Loaded sense from homeassistant.components.sense
2020-05-01 22:45:59 INFO (SyncWorker_19) [homeassistant.loader] Loaded withings from homeassistant.components.withings
2020-05-01 22:45:59 INFO (SyncWorker_1) [homeassistant.loader] Loaded zha from homeassistant.components.zha
2020-05-01 22:45:59 INFO (SyncWorker_6) [homeassistant.loader] Loaded linky from homeassistant.components.linky
2020-05-01 22:45:59 INFO (SyncWorker_7) [homeassistant.loader] Loaded huawei_lte from homeassistant.components.huawei_lte
2020-05-01 22:45:59 INFO (SyncWorker_14) [homeassistant.loader] Loaded rachio from homeassistant.components.rachio
2020-05-01 22:45:59 INFO (SyncWorker_10) [homeassistant.loader] Loaded locative from homeassistant.components.locative
2020-05-01 22:45:59 INFO (SyncWorker_15) [homeassistant.loader] Loaded wwlln from homeassistant.components.wwlln
2020-05-01 22:45:59 INFO (SyncWorker_11) [homeassistant.loader] Loaded iqvia from homeassistant.components.iqvia
2020-05-01 22:45:59 INFO (SyncWorker_17) [homeassistant.loader] Loaded mikrotik from homeassistant.components.mikrotik
2020-05-01 22:45:59 INFO (SyncWorker_4) [homeassistant.loader] Loaded sentry from homeassistant.components.sentry
2020-05-01 22:45:59 INFO (SyncWorker_9) [homeassistant.loader] Loaded nest from homeassistant.components.nest
2020-05-01 22:45:59 INFO (SyncWorker_5) [homeassistant.loader] Loaded velbus from homeassistant.components.velbus
2020-05-01 22:45:59 INFO (SyncWorker_16) [homeassistant.loader] Loaded monoprice from homeassistant.components.monoprice
2020-05-01 22:45:59 INFO (SyncWorker_13) [homeassistant.loader] Loaded ipma from homeassistant.components.ipma
2020-05-01 22:45:59 INFO (SyncWorker_2) [homeassistant.loader] Loaded solaredge from homeassistant.components.solaredge
2020-05-01 22:45:59 INFO (SyncWorker_3) [homeassistant.loader] Loaded wemo from homeassistant.components.wemo
2020-05-01 22:45:59 INFO (SyncWorker_0) [homeassistant.loader] Loaded geofency from homeassistant.components.geofency
2020-05-01 22:45:59 INFO (SyncWorker_8) [homeassistant.loader] Loaded freebox from homeassistant.components.freebox
2020-05-01 22:45:59 INFO (SyncWorker_12) [homeassistant.loader] Loaded abode from homeassistant.components.abode
2020-05-01 22:45:59 INFO (SyncWorker_18) [homeassistant.loader] Loaded nuheat from homeassistant.components.nuheat
2020-05-01 22:45:59 INFO (SyncWorker_19) [homeassistant.loader] Loaded airvisual from homeassistant.components.airvisual
2020-05-01 22:45:59 INFO (SyncWorker_1) [homeassistant.loader] Loaded garmin_connect from homeassistant.components.garmin_connect
2020-05-01 22:45:59 INFO (SyncWorker_6) [homeassistant.loader] Loaded lifx from homeassistant.components.lifx
2020-05-01 22:45:59 INFO (SyncWorker_15) [homeassistant.loader] Loaded vizio from homeassistant.components.vizio
2020-05-01 22:45:59 INFO (SyncWorker_11) [homeassistant.loader] Loaded nut from homeassistant.components.nut
2020-05-01 22:45:59 INFO (SyncWorker_17) [homeassistant.loader] Loaded dialogflow from homeassistant.components.dialogflow
2020-05-01 22:45:59 INFO (SyncWorker_4) [homeassistant.loader] Loaded deconz from homeassistant.components.deconz
2020-05-01 22:45:59 INFO (SyncWorker_9) [homeassistant.loader] Loaded zwave from homeassistant.components.zwave
2020-05-01 22:45:59 INFO (SyncWorker_5) [homeassistant.loader] Loaded doorbird from homeassistant.components.doorbird
2020-05-01 22:45:59 INFO (SyncWorker_16) [homeassistant.loader] Loaded nexia from homeassistant.components.nexia
2020-05-01 22:45:59 INFO (SyncWorker_13) [homeassistant.loader] Loaded vilfo from homeassistant.components.vilfo
2020-05-01 22:45:59 INFO (SyncWorker_14) [homeassistant.loader] Loaded daikin from homeassistant.components.daikin
2020-05-01 22:45:59 INFO (SyncWorker_10) [homeassistant.loader] Loaded coolmaster from homeassistant.components.coolmaster
2020-05-01 22:45:59 INFO (SyncWorker_0) [homeassistant.loader] Loaded roku from homeassistant.components.roku
2020-05-01 22:45:59 INFO (SyncWorker_8) [homeassistant.loader] Loaded iaqualink from homeassistant.components.iaqualink
2020-05-01 22:45:59 INFO (SyncWorker_17) [homeassistant.loader] Loaded sonos from homeassistant.components.sonos
2020-05-01 22:45:59 INFO (SyncWorker_18) [homeassistant.loader] Loaded simplisafe from homeassistant.components.simplisafe
2020-05-01 22:46:00 INFO (SyncWorker_19) [homeassistant.loader] Loaded esphome from homeassistant.components.esphome
2020-05-01 22:46:00 INFO (SyncWorker_1) [homeassistant.loader] Loaded traccar from homeassistant.components.traccar
2020-05-01 22:46:00 INFO (SyncWorker_7) [homeassistant.loader] Loaded netatmo from homeassistant.components.netatmo
2020-05-01 22:46:00 INFO (SyncWorker_2) [homeassistant.loader] Loaded tradfri from homeassistant.components.tradfri
2020-05-01 22:46:00 INFO (SyncWorker_3) [homeassistant.loader] Loaded pvpc_hourly_pricing from homeassistant.components.pvpc_hourly_pricing
2020-05-01 22:46:00 INFO (SyncWorker_6) [homeassistant.loader] Loaded neato from homeassistant.components.neato
2020-05-01 22:46:00 INFO (SyncWorker_15) [homeassistant.loader] Loaded brother from homeassistant.components.brother
2020-05-01 22:46:00 INFO (SyncWorker_11) [homeassistant.loader] Loaded shopping_list from homeassistant.components.shopping_list
2020-05-01 22:46:00 INFO (SyncWorker_12) [homeassistant.loader] Loaded ambiclimate from homeassistant.components.ambiclimate
2020-05-01 22:46:00 INFO (SyncWorker_4) [homeassistant.loader] Loaded twentemilieu from homeassistant.components.twentemilieu
2020-05-01 22:46:00 INFO (SyncWorker_9) [homeassistant.loader] Loaded ipp from homeassistant.components.ipp
2020-05-01 22:46:00 INFO (SyncWorker_5) [homeassistant.loader] Loaded gios from homeassistant.components.gios
2020-05-01 22:46:00 INFO (SyncWorker_16) [homeassistant.loader] Loaded upnp from homeassistant.components.upnp
2020-05-01 22:46:00 INFO (SyncWorker_13) [homeassistant.loader] Loaded geonetnz_quakes from homeassistant.components.geonetnz_quakes
2020-05-01 22:46:00 INFO (SyncWorker_14) [homeassistant.loader] Loaded local_ip from homeassistant.components.local_ip
2020-05-01 22:46:00 INFO (SyncWorker_10) [homeassistant.loader] Loaded owntracks from homeassistant.components.owntracks
2020-05-01 22:46:00 INFO (SyncWorker_0) [homeassistant.loader] Loaded smhi from homeassistant.components.smhi
2020-05-01 22:46:00 INFO (SyncWorker_8) [homeassistant.loader] Loaded ios from homeassistant.components.ios
2020-05-01 22:46:00 INFO (SyncWorker_17) [homeassistant.loader] Loaded twilio from homeassistant.components.twilio
2020-05-01 22:46:00 INFO (SyncWorker_18) [homeassistant.loader] Loaded adguard from homeassistant.components.adguard
2020-05-01 22:46:00 INFO (SyncWorker_19) [homeassistant.loader] Loaded mailgun from homeassistant.components.mailgun
2020-05-01 22:46:00 INFO (SyncWorker_1) [homeassistant.loader] Loaded hangouts from homeassistant.components.hangouts
2020-05-01 22:46:00 INFO (SyncWorker_7) [homeassistant.loader] Loaded hisense_aehw4a1 from homeassistant.components.hisense_aehw4a1
2020-05-01 22:46:00 INFO (SyncWorker_16) [homeassistant.loader] Loaded coronavirus from homeassistant.components.coronavirus
2020-05-01 22:46:00 INFO (SyncWorker_10) [homeassistant.loader] Loaded tellduslive from homeassistant.components.tellduslive
2020-05-01 22:46:00 INFO (SyncWorker_0) [homeassistant.loader] Loaded directv from homeassistant.components.directv
2020-05-01 22:46:00 INFO (SyncWorker_8) [homeassistant.loader] Loaded point from homeassistant.components.point
2020-05-01 22:46:00 INFO (SyncWorker_17) [homeassistant.loader] Loaded wled from homeassistant.components.wled
2020-05-01 22:46:00 INFO (SyncWorker_18) [homeassistant.loader] Loaded elgato from homeassistant.components.elgato
2020-05-01 22:46:00 INFO (SyncWorker_5) [homeassistant.loader] Loaded soma from homeassistant.components.soma
2020-05-01 22:46:01 INFO (SyncWorker_1) [homeassistant.loader] Loaded logi_circle from homeassistant.components.logi_circle
2020-05-01 22:46:01 INFO (SyncWorker_14) [homeassistant.loader] Loaded ifttt from homeassistant.components.ifttt
2020-05-01 22:46:01 INFO (SyncWorker_16) [homeassistant.loader] Loaded solarlog from homeassistant.components.solarlog
2020-05-01 22:46:01 INFO (SyncWorker_15) [homeassistant.loader] Loaded ps4 from homeassistant.components.ps4
2020-05-01 22:46:02 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:46:02 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:46:07 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:46:07 ERROR (MainThread) [hacs.factory] robmarkcole/Hue-remotes-HASS - Repository is archived.
2020-05-01 22:46:10 ERROR (SyncWorker_4) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:46:33 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '11', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:46:33 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:46:38 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:46:41 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:47:04 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:47:04 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:47:09 ERROR (SyncWorker_16) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:47:12 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:47:35 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 22:47:35 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:47:40 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:47:43 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:48:06 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:48:06 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 22:48:11 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:48:14 ERROR (SyncWorker_5) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:48:37 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '11', 'current_consumption': '0.5', 'voltage': '226.0'}
2020-05-01 22:48:37 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 22:48:42 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:48:45 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:48:53 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 22:48:53 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 22:49:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '226.0'}
2020-05-01 22:49:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 22:49:13 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:49:16 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:49:30 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 22:49:30 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 22:49:39 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 22:49:39 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.6'}
2020-05-01 22:49:44 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:49:47 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:50:10 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '11', 'current_consumption': '0.5', 'voltage': '226.0'}
2020-05-01 22:50:10 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 22:50:15 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:50:18 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:50:38 DEBUG (SyncWorker_16) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 22:50:40 DEBUG (SyncWorker_16) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 22:50:41 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 22:50:41 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 22:50:46 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:50:49 ERROR (SyncWorker_12) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:51:00 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 22:51:00 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 22:51:12 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '16', 'current_consumption': '0.3', 'voltage': '224.4'}
2020-05-01 22:51:12 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:51:17 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:51:20 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:51:43 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 22:51:43 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 22:51:48 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:51:51 ERROR (SyncWorker_8) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:52:14 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 22:52:14 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 22:52:19 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:52:22 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:52:40 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Heartbeat timeout, resetting connection
2020-05-01 22:52:45 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 22:52:45 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 22:52:50 ERROR (SyncWorker_15) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:52:53 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:53:10 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Failed to connect to service BRAVIA-4K-GB-01e1f292cc9645303eef77ccbf339324._googlecast._tcp.local., retrying in 5.0s
2020-05-01 22:53:16 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '10', 'current_consumption': '0.3', 'voltage': '224.4'}
2020-05-01 22:53:16 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:53:21 ERROR (SyncWorker_8) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:53:24 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:53:47 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:53:47 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:53:52 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:53:55 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:54:19 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '16', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 22:54:19 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:54:23 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:54:26 ERROR (SyncWorker_12) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:54:49 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '16', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 22:54:49 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:54:54 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:54:57 ERROR (SyncWorker_12) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:55:20 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 22:55:20 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 22:55:25 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:55:28 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:55:39 DEBUG (SyncWorker_18) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 22:55:41 DEBUG (SyncWorker_18) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 22:55:51 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 22:55:51 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:55:56 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:55:59 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:56:22 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 22:56:22 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:56:27 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:56:30 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:56:41 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 22:56:41 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 22:56:53 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:56:53 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:56:58 ERROR (SyncWorker_16) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:57:01 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:57:18 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 22:57:18 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 22:57:24 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.6', 'voltage': '225.1'}
2020-05-01 22:57:24 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 22:57:29 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:57:32 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:57:56 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '11', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 22:57:56 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 22:58:00 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:58:03 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:58:26 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 22:58:26 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:58:31 ERROR (SyncWorker_15) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:58:34 ERROR (SyncWorker_4) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:58:48 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Heartbeat timeout, resetting connection
2020-05-01 22:58:57 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 22:58:57 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:59:01 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for switch.plug_termo (<class 'custom_components.localtuya.switch.TuyaDevice'>) took 4.334 seconds. Please report it to the custom component author.
2020-05-01 22:59:04 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:59:05 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Failed to connect to service BRAVIA-4K-GB-01e1f292cc9645303eef77ccbf339324._googlecast._tcp.local., retrying in 5.0s
2020-05-01 22:59:07 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:59:28 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 22:59:28 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 22:59:35 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:59:38 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 22:59:59 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '11', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 22:59:59 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 23:00:06 ERROR (SyncWorker_5) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:00:09 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:00:30 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.4', 'voltage': '226.0'}
2020-05-01 23:00:30 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:00:37 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:00:40 DEBUG (SyncWorker_11) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 23:00:40 ERROR (SyncWorker_8) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:00:42 DEBUG (SyncWorker_11) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 23:01:01 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:01:02 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:01:08 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:01:11 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:01:32 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 23:01:32 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:01:39 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:01:42 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:02:03 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.5', 'voltage': '223.5'}
2020-05-01 23:02:03 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:02:10 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:02:13 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:02:34 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '223.5'}
2020-05-01 23:02:34 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:02:41 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:02:44 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:03:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '10', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 23:03:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:03:12 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:03:15 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:03:36 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 23:03:36 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:03:43 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:03:46 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:04:07 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 23:04:07 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for switch.plug_cdz (<class 'custom_components.localtuya.switch.TuyaDevice'>) took 0.457 seconds. Please report it to the custom component author.
2020-05-01 23:04:07 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:04:14 ERROR (SyncWorker_16) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:04:17 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:04:38 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '16', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 23:04:38 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:04:45 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:04:48 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:05:09 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 23:05:09 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 23:05:16 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:05:19 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:05:40 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 23:05:40 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:05:41 DEBUG (SyncWorker_16) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 23:05:43 DEBUG (SyncWorker_16) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 23:05:47 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 23:05:47 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 23:05:47 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:05:50 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:06:11 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.4', 'voltage': '226.0'}
2020-05-01 23:06:11 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:06:18 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:06:21 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:06:24 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 23:06:24 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 23:06:42 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.4', 'voltage': '226.0'}
2020-05-01 23:06:42 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:06:49 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:06:52 ERROR (SyncWorker_4) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:07:13 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 23:07:13 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:07:20 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:07:23 ERROR (SyncWorker_4) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:07:44 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:07:44 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:07:51 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:07:54 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:08:15 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:08:16 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:08:22 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:08:25 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:08:46 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '10', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:08:46 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 23:08:53 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:08:56 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:09:17 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:09:17 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:09:24 ERROR (SyncWorker_15) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:09:27 ERROR (SyncWorker_16) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:09:48 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:09:48 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 23:09:55 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:09:58 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:10:19 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '225.1'}
2020-05-01 23:10:19 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '224.3'}
2020-05-01 23:10:26 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:10:29 ERROR (SyncWorker_5) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:10:42 DEBUG (SyncWorker_18) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 23:10:44 DEBUG (SyncWorker_18) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 23:10:50 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 23:10:50 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.0'}
2020-05-01 23:10:57 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:11:00 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:11:21 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '16', 'current_consumption': '0.4', 'voltage': '224.4'}
2020-05-01 23:11:21 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:11:28 ERROR (SyncWorker_15) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:11:31 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:11:52 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.4', 'voltage': '225.1'}
2020-05-01 23:11:52 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '223.3'}
2020-05-01 23:11:59 ERROR (SyncWorker_4) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:12:02 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:12:23 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '224.4'}
2020-05-01 23:12:23 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '222.7'}
2020-05-01 23:12:30 ERROR (SyncWorker_1) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:12:33 ERROR (SyncWorker_8) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:12:54 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '222.9'}
2020-05-01 23:12:54 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '222.7'}
2020-05-01 23:13:01 ERROR (SyncWorker_16) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:13:04 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:13:25 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.4', 'voltage': '222.9'}
2020-05-01 23:13:25 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '222.7'}
2020-05-01 23:13:32 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:13:35 ERROR (SyncWorker_5) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:13:56 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '11', 'current_consumption': '0.4', 'voltage': '223.5'}
2020-05-01 23:13:56 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '222.7'}
2020-05-01 23:14:03 ERROR (SyncWorker_8) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:14:06 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:14:27 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:14:27 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:14:34 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:14:37 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:15:05 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:15:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_cdz is taking over 10 seconds
2020-05-01 23:15:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.plug_cdz fails
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/home/pi/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.homeassistant/custom_components/localtuya/switch.py", line 169, in update
    status = self._device.status()
  File "/home/pi/.homeassistant/custom_components/localtuya/switch.py", line 114, in status
    self._cached_status = self.__get_status()
  File "/home/pi/.homeassistant/custom_components/localtuya/switch.py", line 96, in __get_status
    status = self._device.status()
  File "/home/pi/homeassistant/lib/python3.7/site-packages/pytuya/__init__.py", line 281, in status
    data = self._send_receive(payload)
  File "/home/pi/homeassistant/lib/python3.7/site-packages/pytuya/__init__.py", line 179, in _send_receive
    data = s.recv(1024)
socket.timeout: timed out
2020-05-01 23:15:08 ERROR (SyncWorker_5) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:15:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:15:29 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:15:29 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.6'}
2020-05-01 23:15:36 ERROR (SyncWorker_15) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:15:39 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:15:43 DEBUG (SyncWorker_8) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 23:15:45 DEBUG (SyncWorker_8) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 23:16:00 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.5', 'voltage': '226.7'}
2020-05-01 23:16:00 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:16:07 ERROR (SyncWorker_16) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:16:10 ERROR (SyncWorker_8) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:16:31 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '18', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:16:31 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:16:38 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:16:41 ERROR (SyncWorker_5) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:17:02 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:17:02 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.6'}
2020-05-01 23:17:09 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:17:12 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:17:33 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '227.7'}
2020-05-01 23:17:33 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:17:40 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:17:43 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:18:04 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:18:04 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:18:11 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:18:14 ERROR (SyncWorker_19) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:18:35 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.4', 'voltage': '227.7'}
2020-05-01 23:18:35 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:18:42 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:18:45 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:19:06 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.5', 'voltage': '226.7'}
2020-05-01 23:19:07 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:19:13 ERROR (SyncWorker_0) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:19:16 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:19:37 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:19:37 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:19:44 ERROR (SyncWorker_11) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:19:47 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:20:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '18', 'current_consumption': '0.4', 'voltage': '226.7'}
2020-05-01 23:20:08 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.6'}
2020-05-01 23:20:15 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:20:18 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:20:39 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.6', 'voltage': '227.7'}
2020-05-01 23:20:39 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '227.3'}
2020-05-01 23:20:44 DEBUG (SyncWorker_18) [homeassistant.components.rest.sensor] Updating from http://localhost/bticino.php
2020-05-01 23:20:46 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:20:46 DEBUG (SyncWorker_18) [homeassistant.components.rest.sensor] Data fetched from resource: {"temp":"20.8","umid":"62.0"}
2020-05-01 23:20:49 ERROR (SyncWorker_12) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:21:10 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.5', 'voltage': '227.7'}
2020-05-01 23:21:10 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:21:17 ERROR (SyncWorker_14) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:21:20 ERROR (SyncWorker_18) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:21:41 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '226.7'}
2020-05-01 23:21:41 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:21:48 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:21:51 ERROR (SyncWorker_10) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:22:09 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 23:22:09 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 23:22:12 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '15', 'current_consumption': '0.5', 'voltage': '226.7'}
2020-05-01 23:22:12 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:22:18 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:22:21 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:22:43 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '14', 'current_consumption': '0.5', 'voltage': '227.7'}
2020-05-01 23:22:43 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:22:49 ERROR (SyncWorker_2) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:22:52 ERROR (SyncWorker_13) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:23:14 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '12', 'current_consumption': '0.5', 'voltage': '226.7'}
2020-05-01 23:23:14 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:23:20 ERROR (SyncWorker_3) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:23:22 ERROR (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error reading from socket.
2020-05-01 23:23:22 WARNING (Thread-4) [pychromecast.socket_client] [Tivù soggiorno:8009] Error communicating with socket, resetting connection
2020-05-01 23:23:23 ERROR (SyncWorker_12) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:23:45 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '13', 'current_consumption': '0.5', 'voltage': '226.7'}
2020-05-01 23:23:45 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '225.6'}
2020-05-01 23:23:51 ERROR (SyncWorker_17) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:23:54 ERROR (SyncWorker_4) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:24:16 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '17', 'current_consumption': '0.4', 'voltage': '227.7'}
2020-05-01 23:24:16 DEBUG (MainThread) [custom_components.localtuya.switch] LocalTUYA: {'current': '0', 'current_consumption': '0.0', 'voltage': '226.6'}
2020-05-01 23:24:22 ERROR (SyncWorker_6) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
2020-05-01 23:24:25 ERROR (SyncWorker_9) [pymodbus.client.sync] Connection to (192.168.1.32, 502) failed: [Errno 113] No route to host
